esp_toml_version = 1.0
firmware_images_url = "https://MichaelDu9226.github.io/Talemap_Firmware/bin/"

supported_apps = ["Talemap"]

[Talemap_Firmware]
chipsets = ["ESP32"]
offset = 0x10000
image.esp32 = "talemap_0x10000.bin"
